theme = "onedark"

[editor]
auto-format = true
cursorline = true
completion-timeout = 5
true-color = true

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 300

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.whitespace.render]
space = "all"

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal."="]
t = ":sh mix test"
f = ":sh mix test --only focus"
c = ":sh mix credo --strict"
d = ":sh mix dialyzer"
a = ":sh mix check"

[keys.normal]
"C-s" = ["save_selection", ":fmt", ":w"]
"y" = [":clipboard-yank", "yank"]
"X" = "select_line_above"
"C-a" = "goto_line_start"
"C-f" = "move_char_right"
esc = ["collapse_selection", "keep_primary_selection"]
"A-j" = [ "extend_to_line_bounds", "delete_selection", "paste_after" ]
"A-k" = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ]
"A-J" = [ "extend_to_line_bounds", "yank", "paste_after" ]
"A-K" = [ "extend_to_line_bounds", "yank", "paste_before" ]
"tab" = "goto_next_function"
"S-tab" = "goto_prev_function"
c = ["trim_selections", "change_selection"]
"ret" = ["open_below", "normal_mode"]
"S-ret" = ["open_above", "normal_mode"]
"S-d" = ["ensure_selections_forward", "extend_to_line_end"]
"C-r" = ":reload-all"
"C-," = ":config-open"

[keys.normal."g"]
"v" = ["vsplit", "jump_view_up", "goto_definition"]
"w" = ["save_selection", "goto_word"]

[keys.normal."space"]
"S-f" = "file_picker_in_current_buffer_directory"

[keys.insert]
"C-A" = ["select_mode", "goto_line_start", "exit_select_mode"]
"C-E" = ["select_mode", "goto_line_end", "exit_select_mode"]
"C-e" = ["goto_line_end", "move_char_right"]
"C-a" = "goto_line_start"
"C-f" = "move_char_right"
"C-b" = "move_char_left"
"C-s" = ["commit_undo_checkpoint", ":fmt", ":w"]
"C-space" = "signature_help"

[keys.select]
"y" = [":clipboard-yank", "yank"]
"X" = "select_line_above"
"C-a" = "goto_line_start"
"C-f" = "move_char_right"
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
"A-j" = [ "extend_to_line_bounds", "delete_selection", "paste_after" ]
"A-k" = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ]
"A-J" = [ "extend_to_line_bounds", "yank", "paste_after" ]
"A-K" = [ "extend_to_line_bounds", "yank", "paste_before" ]
