[language-server.typos]
command = "/opt/homebrew/bin/typos-lsp"
config.diagnosticSeverity = "Warning"
environment = {"ELIXIR_LOG" = "info"} 

[language-server.lexical]
command = "/Users/elfenlaid/Code/lexical/_build/dev/package/lexical/bin/start_lexical.sh"

[language-server.nextls]
command = "/opt/homebrew/bin/nextls"
args = ["--stdio=true"]

[[language]]
name = "elixir"
auto-format = true
scope = "source.elixir"
language-servers = ["lexical", "typos"]

[[language]]
name = "heex"
auto-format = true
language-servers = ["lexical", "typos"]
